
package ws.invoice.v21;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-22T22:29:14.077+01:00
 * Generated source version: 3.0.1
 * 
 */
public final class InvoicePortType_InvoicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://soapui.cookbook.samples/contract/invoice", "InvoiceServiceV2");

    private InvoicePortType_InvoicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InvoiceServiceV2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InvoiceServiceV2 ss = new InvoiceServiceV2(wsdlURL, SERVICE_NAME);
        InvoicePortType port = ss.getInvoicePort();  
        
        {
        System.out.println("Invoking createInvoice...");
        java.lang.String _createInvoice_invoiceNoVal = "";
        javax.xml.ws.Holder<java.lang.String> _createInvoice_invoiceNo = new javax.xml.ws.Holder<java.lang.String>(_createInvoice_invoiceNoVal);
        java.lang.String _createInvoice_company = "";
        double _createInvoice_amount = 0.0;
        javax.activation.DataHandler _createInvoice_file = null;
        port.createInvoice(_createInvoice_invoiceNo, _createInvoice_company, _createInvoice_amount, _createInvoice_file);

        System.out.println("createInvoice._createInvoice_invoiceNo=" + _createInvoice_invoiceNo.value);

        }
        {
        System.out.println("Invoking getInvoice...");
        java.lang.String _getInvoice_invoiceNoVal = "";
        javax.xml.ws.Holder<java.lang.String> _getInvoice_invoiceNo = new javax.xml.ws.Holder<java.lang.String>(_getInvoice_invoiceNoVal);
        javax.xml.ws.Holder<java.lang.String> _getInvoice_company = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.Double> _getInvoice_amount = new javax.xml.ws.Holder<java.lang.Double>();
        javax.xml.ws.Holder<javax.activation.DataHandler> _getInvoice_file = new javax.xml.ws.Holder<javax.activation.DataHandler>();
        port.getInvoice(_getInvoice_invoiceNo, _getInvoice_company, _getInvoice_amount, _getInvoice_file);

        System.out.println("getInvoice._getInvoice_invoiceNo=" + _getInvoice_invoiceNo.value);
        System.out.println("getInvoice._getInvoice_company=" + _getInvoice_company.value);
        System.out.println("getInvoice._getInvoice_amount=" + _getInvoice_amount.value);
        System.out.println("getInvoice._getInvoice_file=" + _getInvoice_file.value);

        }

        System.exit(0);
    }

}
