/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ws.invoice.v21;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Logger;

import javax.activation.DataHandler;
import javax.mail.util.ByteArrayDataSource;

/**
 * This class was generated by Apache CXF 3.0.1 2014-09-22T22:29:14.146+01:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(serviceName = "InvoiceServiceV2", portName = "InvoicePort", targetNamespace = "http://soapui.cookbook.samples/contract/invoice", wsdlLocation = "invoice_v2_1.wsdl", endpointInterface = "ws.invoice.v21.InvoicePortType")
public class InvoicePortImpl implements InvoicePortType {

	private static final Logger LOG = Logger.getLogger(InvoicePortImpl.class
			.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see ws.invoice.v21.InvoicePortType#createInvoice(java.lang.String
	 * invoiceNo ,)java.lang.String company ,)double amount
	 * ,)javax.activation.DataHandler file )*
	 */
	public void createInvoice(javax.xml.ws.Holder<java.lang.String> invoiceNo,
			java.lang.String company, double amount,
			javax.activation.DataHandler file) {
		LOG.info("Executing operation createInvoice");

		System.out.println("Invoice No: " + invoiceNo.value);
		System.out.println("Company: " + company);
		System.out.println("Amount: " + amount);

		System.out.println(file);
		if (file != null) {
			System.out.println(file.getName());
			System.out.println(file.getContentType());
		}
		try {
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see ws.invoice.v21.InvoicePortType#getInvoice(java.lang.String invoiceNo
	 * ,)java.lang.String company ,)java.lang.Double amount
	 * ,)javax.activation.DataHandler file )*
	 */
	public void getInvoice(javax.xml.ws.Holder<java.lang.String> invoiceNo,
			javax.xml.ws.Holder<java.lang.String> company,
			javax.xml.ws.Holder<java.lang.Double> amount,
			javax.xml.ws.Holder<javax.activation.DataHandler> file) {
		
		LOG.info("Executing operation getInvoice");
		System.out.println("Invoice no: "+invoiceNo.value);
		
		try {
			company.value = "company";
			System.out.println("Company: "+company.value);
			amount.value = 100d;
			System.out.println("Amount: "+amount);

			String attachmentFileName = "/temp/invoice1.pdf";
			System.out.println("Attachment: "+attachmentFileName);
			File attachment = new File(attachmentFileName);
			InputStream attachmentInputStream = new FileInputStream(attachment);
			ByteArrayOutputStream responseOutputStream = new ByteArrayOutputStream();
			copyInputStreamToOutputStream(attachmentInputStream,
					responseOutputStream);
			System.out.println("Attachment size: "
					+ responseOutputStream.size());
			attachmentInputStream.close();
			file.value = new DataHandler(new ByteArrayDataSource(
					responseOutputStream.toByteArray(), "application/pdf"));

		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	private int copyInputStreamToOutputStream(final InputStream input,
			final OutputStream output) throws IOException {
		final byte[] buffer = new byte[4096];
		int n = 0;
		n = input.read(buffer);
		int total = 0;
		while (-1 != n) {
			output.write(buffer, 0, n);
			total += n;
			n = input.read(buffer);
		}
		return total;
	}
}
