
package ws.invoice.v21;

import javax.xml.ws.Binding;
import javax.xml.ws.Endpoint;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-22T22:29:14.173+01:00
 * Generated source version: 3.0.1
 * 
 */
 
public class InvoicePortType_InvoicePort_Server{

    protected InvoicePortType_InvoicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new InvoicePortImpl();
        String address = "http://localhost:9000/mockInvoicePortBinding";
        Endpoint ep = Endpoint.publish(address, implementor);
        Binding binding = ep.getBinding();        
        ((SOAPBinding)binding).setMTOMEnabled(true);  
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new InvoicePortType_InvoicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
