package ws.invoice.v3;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * Retrieve and Create An Invoice.
 * 		
 *
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-18T13:37:51.126+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://soapui.cookbook.samples/contract/invoice", name = "InvoicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface InvoicePortType {

    @Oneway
    @RequestWrapper(localName = "deleteInvoice", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v3.InvoiceRefType")
    @WebMethod(action = "http://soapui.cookbook.samples/deleteInvoiceRequest/request")
    public void deleteInvoice(
        @WebParam(name = "invoiceNo", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        java.lang.String invoiceNo
    );

    @WebResult(name = "invoiceNo", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
    @RequestWrapper(localName = "createInvoice", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v3.InvoiceDocumentType")
    @WebMethod(action = "http://soapui.cookbook.samples/createInvoiceRequest/request")
    @ResponseWrapper(localName = "Acknowledgement", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v3.InvoiceRefType")
    public java.lang.String createInvoice(
        @WebParam(name = "id", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        java.lang.String id,
        @WebParam(name = "customerRef", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        java.lang.String customerRef,
        @WebParam(name = "amount", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        double amount,
        @WebParam(name = "dueDate", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.datatype.XMLGregorianCalendar dueDate
    );

    @RequestWrapper(localName = "retrieveInvoice", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v3.InvoiceRefType")
    @WebMethod(action = "http://soapui.cookbook.samples/retrieveInvoiceRequest/request")
    @ResponseWrapper(localName = "InvoiceDocument", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v3.InvoiceDocumentType")
    public void retrieveInvoice(
        @WebParam(name = "invoiceNo", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        java.lang.String invoiceNo,
        @WebParam(mode = WebParam.Mode.OUT, name = "id", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.ws.Holder<java.lang.String> id,
        @WebParam(mode = WebParam.Mode.OUT, name = "customerRef", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.ws.Holder<java.lang.String> customerRef,
        @WebParam(mode = WebParam.Mode.OUT, name = "amount", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.ws.Holder<java.lang.Double> amount,
        @WebParam(mode = WebParam.Mode.OUT, name = "dueDate", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> dueDate
    );

    @WebResult(name = "invoiceNo", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
    @RequestWrapper(localName = "updateInvoice", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v3.InvoiceDocumentType")
    @WebMethod(action = "http://soapui.cookbook.samples/updateInvoiceRequest/request")
    @ResponseWrapper(localName = "Acknowledgement", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v3.InvoiceRefType")
    public java.lang.String updateInvoice(
        @WebParam(name = "id", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        java.lang.String id,
        @WebParam(name = "customerRef", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        java.lang.String customerRef,
        @WebParam(name = "amount", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        double amount,
        @WebParam(name = "dueDate", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.datatype.XMLGregorianCalendar dueDate
    );
}
