
package ws.invoice.v3;

import javax.xml.ws.Endpoint;

import org.h2.tools.DeleteDbFiles;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-18T13:37:51.139+01:00
 * Generated source version: 3.0.1
 * 
 */
 
public class InvoicePortType_InvoicePort_Server{

    protected InvoicePortType_InvoicePort_Server() throws java.lang.Exception {
        System.out.println("Starting InvoiceV3 Server");
        Object implementor = new InvoicePortImpl();
        String address = "http://localhost:9003/ws/invoice/v3";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
    	
    	//This is a simple option for tearing down the service's test data i.e. this deletes the 
    	//database file every time the service is started.
    	//System.out.println("Tearing down test db: " + InvoicePortImpl.DB_FILE_LOCATION);
    	//DeleteDbFiles.execute(".", InvoicePortImpl.DB_FILE_LOCATION, true);
    	
    	new InvoicePortType_InvoicePort_Server();
        System.out.println("Server ready, will close automatically in 30 minutes..."); 
        
        //Service timeout set to 30 minutes
        Thread.sleep(30 * 60 * 1000); 
        System.out.println("Server InvoiceV3 exiting");
        System.exit(0);
    }
}
