
package ws.invoice.v2;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-15T16:25:09.648+01:00
 * Generated source version: 3.0.1
 * 
 */
 
public class InvoicePortType_InvoicePort_Server{

    protected InvoicePortType_InvoicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new InvoicePortImpl();
        String address = "http://localhost:9002/ws/invoice/v2";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new InvoicePortType_InvoicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
