package ws.invoice.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * Get and Create An Invoice.
 * 		
 *
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-15T16:25:09.636+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://soapui.cookbook.samples/contract/invoice", name = "InvoicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface InvoicePortType {

    @RequestWrapper(localName = "createInvoice", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v2.InvoiceDocumentType")
    @WebMethod(action = "http://soapui.cookbook.samples/createInvoiceRequest/request")
    @ResponseWrapper(localName = "Acknowledgement", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v2.InvoiceRefType")
    public void createInvoice(
        @WebParam(mode = WebParam.Mode.INOUT, name = "invoiceNo", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.ws.Holder<java.lang.String> invoiceNo,
        @WebParam(name = "company", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        java.lang.String company,
        @WebParam(name = "amount", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        double amount
    );

    @RequestWrapper(localName = "getInvoice", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v2.InvoiceRefType")
    @WebMethod(action = "http://soapui.cookbook.samples/getInvoiceRequest/request")
    @ResponseWrapper(localName = "InvoiceDocument", targetNamespace = "http://soapui.cookbook.samples/schema/invoice", className = "ws.invoice.v2.InvoiceDocumentType")
    public void getInvoice(
        @WebParam(mode = WebParam.Mode.INOUT, name = "invoiceNo", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.ws.Holder<java.lang.String> invoiceNo,
        @WebParam(mode = WebParam.Mode.OUT, name = "company", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.ws.Holder<java.lang.String> company,
        @WebParam(mode = WebParam.Mode.OUT, name = "amount", targetNamespace = "http://soapui.cookbook.samples/schema/invoice")
        javax.xml.ws.Holder<java.lang.Double> amount
    );
}
