
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ws.invoice.v2;

import java.util.logging.Logger;
import java.util.Map;
import java.util.HashMap;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-15T16:25:09.577+01:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "InvoiceServiceV2",
                      portName = "InvoicePort",
                      targetNamespace = "http://soapui.cookbook.samples/contract/invoice",
                      wsdlLocation = "invoice_v2.wsdl",
                      endpointInterface = "ws.invoice.v2.InvoicePortType")
                      
public class InvoicePortImpl implements InvoicePortType {

    private static final Logger LOG = Logger.getLogger(InvoicePortImpl.class.getName());
	private Map<String, Invoice> invoices = new HashMap<String, Invoice>();

    /* (non-Javadoc)
     * @see ws.invoice.v2.InvoicePortType#createInvoice(java.lang.String  invoiceNo ,)java.lang.String  company ,)double  amount )*
     */
    public void createInvoice(javax.xml.ws.Holder<java.lang.String> invoiceNo,java.lang.String company,double amount) { 
        LOG.info("Executing operation createInvoice");
        System.out.println(invoiceNo.value);
        System.out.println(company);
        System.out.println(amount);
        
        try {
        	Invoice invoice = new Invoice();
			invoice.setInvoiceNo(invoiceNo.value);
			invoice.setCompanyName(company);
			invoice.setAmount(amount);
			invoices.put(invoiceNo.value, invoice);
			
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ws.invoice.v2.InvoicePortType#getInvoice(java.lang.String  invoiceNo ,)java.lang.String  company ,)java.lang.Double  amount )*
     */
    public void getInvoice(javax.xml.ws.Holder<java.lang.String> invoiceNo,javax.xml.ws.Holder<java.lang.String> company,javax.xml.ws.Holder<java.lang.Double> amount) { 
        LOG.info("Executing operation getInvoice");
        System.out.println(invoiceNo.value);
        try {
        	Invoice invoice = invoices.get(invoiceNo.value);
        	if (invoice!=null) {
            	invoiceNo.value = invoice.getInvoiceNo();
            	company.value = invoice.getCompanyName();
            	amount.value = invoice.getAmount();
            }
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
