
package ws.invoice.v1;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-09T17:15:30.747Z
 * Generated source version: 3.0.1
 * 
 */
 
public class InvoicePortType_InvoicePort_Server{

    protected InvoicePortType_InvoicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new InvoicePortImpl();
        String address = "http://localhost:9001/ws/invoice/v1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new InvoicePortType_InvoicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
