
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ws.invoice.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-09T17:15:30.580Z
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "InvoiceServiceV1",
                      portName = "InvoicePort",
                      targetNamespace = "http://soapui.cookbook.samples/contract/invoice",
                      wsdlLocation = "invoice_v1.wsdl",
                      endpointInterface = "ws.invoice.v1.InvoicePortType")
                      
public class InvoicePortImpl implements InvoicePortType {

    private static final Logger LOG = Logger.getLogger(InvoicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see ws.invoice.v1.InvoicePortType#getInvoice(java.lang.String  invoiceNo ,)java.lang.String  company ,)java.lang.Double  amount )*
     */
    public void getInvoice(javax.xml.ws.Holder<java.lang.String> invoiceNo,javax.xml.ws.Holder<java.lang.String> company,javax.xml.ws.Holder<java.lang.Double> amount) { 
        LOG.info("Executing operation getInvoice");
        System.out.println(invoiceNo.value);
        try {
            java.lang.String companyValue = "";
            company.value = companyValue;
            java.lang.Double amountValue = null;
            amount.value = amountValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
